# Generated by Django 4.0.3 on 2022-03-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1224)),
                ('email', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=12)),
                ('desc', models.TextField(max_length=122225)),
                ('date', models.DateField()),
            ],
        ),
    ]
