# Generated by Django 4.0.3 on 2022-03-11 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phonenumber',
        ),
    ]
